name: indotaste
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4
  flutter_svg: ^0.22.0
  simple_shadow: ^0.2.0

  cupertino_icons: ^1.0.2
  dio: ^5.1.2
  awesome_dialog: ^2.2.1
  # progress_dialog: ^1.2.4
  sn_progress_dialog: ^1.1.3
  http: ^0.13.6
  shared_preferences: ^2.1.2
  sqflite: ^2.2.8+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/icons/
    - assets/others/
